spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/WangShanJava/springcloudconfig/
          search-paths: respo
          username: 386851725@qq.com
          password: Ming2311066389
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
